name: Flask CI/CD with Docker

on:
  push:
    branches: ["main"]   # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Python for testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies & test
      - name: Install dependencies & test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import flask; print('✅ Flask import successful')"

      # Step 4: Deploy to server via SSH & Docker
      - name: Deploy with Docker
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "== Starting Deployment =="
            whoami
            pwd
            ls -la /home/ubuntu

            # Go to your Flask app folder on the server
            cd /home/ubuntu/hello-flask-app

            # Ensure latest code
            git reset --hard
            git pull origin main

            # Show Docker version & running containers for debug
            docker --version
            docker ps -a

            # Build Docker image
            docker build -t flaskapp .

            # Stop & remove old container if exists
            docker stop flaskapp || true
            docker rm flaskapp || true

            # Run new container
            docker run -d --name flaskapp -p 5000:5000 flaskapp
